import streamlit as st

with st.sidebar:
    menu = st.popover("Menu")
    menu.markdown("###### Line1")
    menu.markdown("###### Line2")
    menu.markdown("###### Line3")
    menu.markdown("###### Line4")
    menu.markdown("###### Line5")
    menu.markdown("###### Line6")
    menu.markdown("###### Line7")
    menu.markdown("###### Line8")
    menu.markdown("###### Line9")
    menu.markdown("###### Line10")
    menu.markdown("###### Line11")
    menu.markdown("###### Line13")
    menu.markdown("###### Line14")
    menu.markdown("###### Line15")
    menu.markdown("###### Line16")
    menu.markdown("###### Line18")
    menu.markdown("###### Line19")
    menu.markdown("###### Line20")
    menu.markdown("###### Line21")
    menu.markdown("###### Line22")
    
    menu2 = st.popover("Menu")
    menu2.markdown("###### Line1")
    menu2.markdown("###### Line2")
    menu2.markdown("###### Line3")
    menu2.markdown("###### Line4")
    menu2.markdown("###### Line5")
    menu2.markdown("###### Line6")
    menu2.markdown("###### Line7")
    menu2.markdown("###### Line8")
    menu2.markdown("###### Line9")
