from typing import Dict, List, Optional, TypedDict

"""
These types represent the structure of the outputted .json file that is
generated by pytest-benchmark.
"""


class CPUInfo(TypedDict):
    python_version: str
    cpuinfo_version: List[int]
    cpuinfo_version_string: str
    arch: str
    bits: int
    count: int
    arch_string_raw: str
    vendor_id_raw: str
    brand_raw: str
    hz_advertised_friendly: str
    hz_actual_friendly: str
    hz_advertised: List[int]
    hz_actual: List[int]
    stepping: int
    model: int
    family: int
    flags: List[str]
    l3_cache_size: int
    l2_cache_size: int
    l1_data_cache_size: int
    l1_instruction_cache_size: int
    l2_cache_line_size: int
    l2_cache_associativity: int


class MachineInfo(TypedDict):
    node: str
    processor: str
    machine: str
    python_compiler: str
    python_implementation: str
    python_implementation_version: str
    python_version: str
    python_build: List[str]
    release: str
    system: str
    cpu: CPUInfo


class CommitInfo(TypedDict):
    id: str
    time: str
    author_time: str
    dirty: bool
    project: str
    branch: str


class BenchmarkOptions(TypedDict):
    disable_gc: bool
    timer: str
    min_rounds: int
    max_time: float
    min_time: float
    warmup: bool


class BenchmarkStats(TypedDict):
    min: float
    max: float
    mean: float
    stddev: float
    rounds: int
    median: float
    iqr: float
    q1: float
    q3: float
    iqr_outliers: int
    stddev_outliers: int
    outliers: str
    ld15iqr: float
    hd15iqr: float
    ops: float
    total: float
    iterations: int


class PytestBenchmarkRun(TypedDict):
    group: Optional[str]
    name: str
    fullname: str
    params: Optional[str]
    param: Optional[str]
    extra_info: Dict[str, any]
    options: BenchmarkOptions
    stats: BenchmarkStats


class OutputJson(TypedDict):
    machine_info: MachineInfo
    commit_info: CommitInfo
    benchmarks: List[PytestBenchmarkRun]
    datetime: str
    version: str
